name: omelette
description: A library that makes handling remote response easier.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
